name: LaTeX build (fast)

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pygments for minted
        run: |
          apk update
          apk add --no-cache python3 py3-pip py3-pygments zip unzip

      - name: Compile with latexmk
        id: compile
        continue-on-error: true
        run: |
          set -x
          latexmk -pdf -interaction=nonstopmode -file-line-error --shell-escape itManual.tex || true

      - name: Show first LaTeX error
        if: always()
        run: |
          echo "---- Searching for first LaTeX error in itManual.log ----"
          if [ -f itManual.log ]; then
            LINE=$(grep -n -a -E '^(!|.*LaTeX Error:)' itManual.log | head -1 | cut -d: -f1 || true)
            if [ -n "$LINE" ]; then
              START=$((LINE>20 ? LINE-20 : 1))
              END=$((LINE+40))
              sed -n "${START},${END}p" itManual.log
            else
              echo "No obvious error lines; showing last 200 lines:"
              tail -n 200 itManual.log
            fi
          else
            echo "itManual.log not found."
          fi

      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: itManual-pdf
          path: itManual.pdf
          if-no-files-found: warn
          retention-days: 14

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: |
            itManual.log
            itManual.fls
            itManual.fdb_latexmk
            *.aux
            *.toc
            *.lof
            *.lot
            _*.minted*
          if-no-files-found: warn
          retention-days: 14
