name: Build LaTeX and Commit PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write version.tex
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          DATE="$(date -u +'%Y-%m-%d')"
          cat > version.tex <<EOF
          \newcommand{\VERSION}{Version ${GITHUB_RUN_NUMBER} (commit ${SHORT_SHA}, ${DATE} UTC)}
          EOF

      - name: Build PDF with latexmk (minted + shell-escape)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: itManual.tex
          args: -pdf -interaction=nonstopmode -file-line-error -shell-escape
          # Alpine package name:
          extra_system_packages: py3-pygments

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: itManual
          path: itManual.pdf

      - name: Commit PDF back to repo
        if: ${{ success() }}
        run: |
          git checkout "${GITHUB_REF_NAME}"
          git pull --rebase origin "${GITHUB_REF_NAME}" || true

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add itManual.pdf
          if ! git diff --cached --quiet; then
            git commit -m "CI: add itManual.pdf for ${GITHUB_SHA::7} (run ${GITHUB_RUN_NUMBER})"
            git push origin "${GITHUB_REF_NAME}"
          else
            echo "No PDF changes to commit."
          fi
