name: Build LaTeX PDF

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # keep history for commit count

      - name: Compute version info
        id: ver
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

      - name: Write version.tex (defines \VERSION)
        run: |
          echo "\\newcommand{\\VERSION}{v${{ steps.ver.outputs.commit_count }}-${{ steps.ver.outputs.short_sha }}}" > version.tex

      # Build with latex-action v3 (containerized TeX Live)
      - name: Build PDF (itManual.tex)
      # Uses ghcr.io/xu-cheng/texlive-full:latest (Alpine-based)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: itManual.tex
          # pdfLaTeX + minted needs shell-escape:
          args: -pdf -shell-escape -file-line-error -interaction=nonstopmode

          # Install OS packages inside the container (Alpine package names!)
          extra_system_packages: >-
            python3
            py3-pip
            py3-pygments
            zip

          # Install TeX packages before compiling
          pre_compile: |
            tlmgr update --self
            tlmgr install \
              amsfonts amsmath \
              minted xcolor hyperref geometry etoolbox \
              pgf listings fancyvrb tcolorbox fvextra catchfile \
              xstring ifplatform grffile upquote \
              titlesec mathtools biblatex csquotes


      - name: Collect outputs
        run: |
          mkdir -p build
          cp itManual.pdf build/ || true
          ZIPNAME="itManual_v${{ steps.ver.outputs.commit_count }}-${{ steps.ver.outputs.short_sha }}.zip"
          (cd build && zip -r "$ZIPNAME" itManual.pdf)

      - name: Upload artifact (download from Actions page)
        uses: actions/upload-artifact@v4
        with:
          name: pdf-build
          path: build/

      - name: Commit PDF back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: add PDF v${{ steps.ver.outputs.commit_count }}-${{ steps.ver.outputs.short_sha }}"
          file_pattern: build/*.pdf build/*.zip
          add_options: '--force'
